# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtable',
            name='latitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='locationtable',
            name='longitude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
