# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_auto_20161130_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtable',
            name='location',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
