# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20161123_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='fb_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
