# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_authuser_fb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
