# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20161125_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='usertype',
            field=models.CharField(choices=[('shop', ['shop']), ('user', ['user'])], max_length=50),
        ),
    ]
