# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-18 05:14
from __future__ import unicode_literals

import Category.models
import Category.thumbs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', Category.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=Category.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', Category.thumbs.ImageWithThumbsField(blank=True, null=True, upload_to=Category.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('features', models.CharField(max_length=250)),
                ('shop_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='categorytable',
            name='maincategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.MainCategoryTable'),
        ),
    ]
