# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_subcategorytable_category'),
        ('Shop', '0002_auto_20161130_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoptable',
            name='shop_type',
        ),
        migrations.AddField(
            model_name='shoptable',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Category.MainCategoryTable'),
            preserve_default=False,
        ),
    ]
